-- MySQL Script generated by MySQL Workbench
-- Sun Mar 12 19:18:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petlovers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petlovers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petlovers` DEFAULT CHARACTER SET utf8 ;
USE `petlovers` ;

-- -----------------------------------------------------
-- Table `petlovers`.`tipos_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`tipos_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `id_tipo_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_usuarios_tipos_usuario_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipos_usuario`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `petlovers`.`tipos_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`enderecos` (
  `id` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`telefones` (
  `id` INT NOT NULL,
  `ddd` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`enderecos_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`enderecos_has_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_endereco` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`, `id_endereco`, `id_usuario`),
  INDEX `fk_enderecos_has_usuarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_enderecos_has_usuarios_enderecos1_idx` (`id_endereco` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_has_usuarios_enderecos1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `petlovers`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecos_has_usuarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `petlovers`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`telefones_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`telefones_has_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefones_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `telefones_id`, `usuarios_id`),
  INDEX `fk_telefones_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_telefones_has_usuarios_telefones1_idx` (`telefones_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_has_usuarios_telefones1`
    FOREIGN KEY (`telefones_id`)
    REFERENCES `petlovers`.`telefones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefones_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `petlovers`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_dono` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `idade` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `raca` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `id_dono`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pets_usuarios1_idx` (`id_dono` ASC) VISIBLE,
  CONSTRAINT `fk_pets_usuarios1`
    FOREIGN KEY (`id_dono`)
    REFERENCES `petlovers`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`tipos_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`tipos_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_tipo_documento` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `id_usuario`, `id_tipo_documento`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_documentos_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_documentos_tipos_documento1_idx` (`id_tipo_documento` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `petlovers`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_tipos_documento1`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `petlovers`.`tipos_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`fotos` (
  `id` INT NOT NULL,
  `id_usuario` INT NULL,
  `id_pet` INT NULL,
  `foto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `id_usuario`, `id_pet`),
  INDEX `fk_fotos_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_fotos_pets1_idx` (`id_pet` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `petlovers`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fotos_pets1`
    FOREIGN KEY (`id_pet`)
    REFERENCES `petlovers`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`doencas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`doencas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pet` INT NOT NULL,
  `nome_da_doenca` VARCHAR(100) NULL,
  `descricao` VARCHAR(450) NULL,
  PRIMARY KEY (`id`, `id_pet`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_doencas_pets1_idx` (`id_pet` ASC) VISIBLE,
  CONSTRAINT `fk_doencas_pets1`
    FOREIGN KEY (`id_pet`)
    REFERENCES `petlovers`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`tratamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`tratamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pet` INT NOT NULL,
  `tratamento` VARCHAR(500) NOT NULL,
  `data_tratamento` VARCHAR(45) NOT NULL,
  `custo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `id_pet`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tratamentos_pets1_idx` (`id_pet` ASC) VISIBLE,
  CONSTRAINT `fk_tratamentos_pets1`
    FOREIGN KEY (`id_pet`)
    REFERENCES `petlovers`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`consultas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pet` INT NOT NULL,
  `id_func_responsavel` INT NOT NULL,
  `data_consulta` DATETIME NULL,
  `horario_consulta` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `id_pet`, `id_func_responsavel`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_consultas_usuarios1_idx` (`id_func_responsavel` ASC) VISIBLE,
  INDEX `fk_consultas_pets1_idx` (`id_pet` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_usuarios1`
    FOREIGN KEY (`id_func_responsavel`)
    REFERENCES `petlovers`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_pets1`
    FOREIGN KEY (`id_pet`)
    REFERENCES `petlovers`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(450) NULL,
  `preco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(450) NULL,
  `preco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petlovers`.`consumidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petlovers`.`consumidos` (
  `id` INT NOT NULL,
  `id_produto` INT NULL,
  `id_servico` INT NULL,
  `id_pet` INT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`, `id_produto`, `id_servico`, `id_pet`, `id_usuario`),
  INDEX `fk_consumidos_produtos1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_consumidos_servicos1_idx` (`id_servico` ASC) VISIBLE,
  INDEX `fk_consumidos_pets1_idx` (`id_pet` ASC) VISIBLE,
  INDEX `fk_consumidos_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_consumidos_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `petlovers`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumidos_servicos1`
    FOREIGN KEY (`id_servico`)
    REFERENCES `petlovers`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumidos_pets1`
    FOREIGN KEY (`id_pet`)
    REFERENCES `petlovers`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumidos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `petlovers`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
